### ISSUE TITLE
Library IPTV

### ISSUE THREAD

**Issue by andeerson** [tylerrichey/iptvm3uplaylist#2]
Library
Good note tylerrichey,
Friend you have a source code of the project for study, because I am an exciting programmer, I liked your library.
I'm having difficulty applying the library, I would like to playlisy and run the videos

Thank you!

**Comment by andeerson** [comment]
This library of error while downloading List.
Can you help me?

**Comment by tylerrichey** [comment]
Can you post the exception?

**Comment by andeerson** [comment]
Need a project to study, can you help me? Please!
I'm having trouble!
